name: 'Embold Github Actions'
description: 'Embold helps you find security vulnerabilities, code issues, design anti patterns, duplication and metrics in your source code.'
inputs:
  embold-url:
    description: 'URL of your Embold Server instance'
    required: true
  embold-token:
    description: 'Embold Access Token corresponding to your Embold Server'
    required: true
  repo-config:
    description: 'Repository configuration JSON used as settings while running the scan'
    required: true
  repo-uid:
    description: 'UID of the repository on Embold Server, where results will be published'
    required: true
  verbose:
    description: 'Enable verbose logging (default is disabled)'
    required: false
runs:
  using: 'docker'
#   image: 'docker://embold/embold-cli:latest'
  image: 'Dockerfile'
  args:
    - ${{ inputs.embold-url }}
    - ${{ inputs.embold-token }}
    - ${{ inputs.repo-config }}
    - ${{ inputs.repo-uid }}
    - ${{ inputs.verbose }}
    branding:
  icon: 'play (triangle)'  
  color: 'orange'
